name: firebase_analytics
description: how to use the firebase_analytics plugin.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  firebase_analytics_platform_interface: ^3.1.2
  firebase_analytics_web: ^0.4.0+9
  firebase_core: ^1.14.0
  firebase_core_platform_interface: ^4.2.5
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true